### ISSUE TITLE
在

### ISSUE THREAD

**Issue by z15268334855** [DangoSky/cloud-music#1]
你好  我想请问一下http://dangosky.com:3000/banner这个接口是从哪里获取的  还有其他的问题 如果方便微信  z1198060316

**Comment by DangoSky** [comment]
@z15268334855 是直接调用这个[api](https://github.com/Binaryify/NeteaseCloudMusicApi)的，具体你可以参考它的[文档说明](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%E5%AE%89%E8%A3%85)。我不过是把它挂到了我自己的服务器上而已，你需要的话也可以直接用我这个，但带宽小可能会比较慢。
